package sage300

import "time"

type GLAccounts []GLAccount

type GLAccount struct {
	UnformattedAccount             string        `json:"UnformattedAccount"`
	DateCreated                    time.Time     `json:"DateCreated"`
	Description                    string        `json:"Description"`
	AccountType                    string        `json:"AccountType"`
	NormalBalanceDRCR              string        `json:"NormalBalanceDRCR"`
	Status                         string        `json:"Status"`
	PostToAccount                  string        `json:"PostToAccount"`
	QuantitiesAllowed              string        `json:"QuantitiesAllowed"`
	UnitOfMeasure                  string        `json:"UnitOfMeasure"`
	AllocationsAllowed             string        `json:"AllocationsAllowed"`
	AllocOffsetAccount             string        `json:"AllocOffsetAccount"`
	AllocSourceType                string        `json:"AllocSourceType"`
	Multicurrency                  string        `json:"Multicurrency"`
	SpecificCurrency               string        `json:"SpecificCurrency"`
	ControlAccount                 string        `json:"ControlAccount"`
	AllocationPercentTotal         float64       `json:"AllocationPercentTotal"`
	StructureCode                  string        `json:"StructureCode"`
	YearLastClosed                 int           `json:"YearLastClosed"`
	AccountNumber                  string        `json:"AccountNumber"`
	AccountSegmentCode1            string        `json:"AccountSegmentCode1"`
	AccountSegmentCode2            string        `json:"AccountSegmentCode2"`
	AccountSegmentCode3            string        `json:"AccountSegmentCode3"`
	AccountSegmentCode4            string        `json:"AccountSegmentCode4"`
	AccountSegmentCode5            string        `json:"AccountSegmentCode5"`
	AccountSegmentCode6            string        `json:"AccountSegmentCode6"`
	AccountSegmentCode7            string        `json:"AccountSegmentCode7"`
	AccountSegmentCode8            string        `json:"AccountSegmentCode8"`
	AccountSegmentCode9            string        `json:"AccountSegmentCode9"`
	AccountSegmentCode10           string        `json:"AccountSegmentCode10"`
	SegmentCode                    string        `json:"SegmentCode"`
	PostToSegmentID                string        `json:"PostToSegmentID"`
	DefaultCurrencyCode            string        `json:"DefaultCurrencyCode"`
	NumberOfOptionalFields         int           `json:"NumberOfOptionalFields"`
	TransactionOptionalFields      int           `json:"TransactionOptionalFields"`
	ProcessSwitch                  string        `json:"ProcessSwitch"`
	AccountGroupCode               string        `json:"AccountGroupCode"`
	AccountGroupSortCode           string        `json:"AccountGroupSortCode"`
	RollupSwitch                   string        `json:"RollupSwitch"`
	RollupMemberNonRollup          string        `json:"RollupMemberNonRollup"`
	AcctSelectorFromAccount        string        `json:"AcctSelectorFromAccount"`
	AcctSelectorToAccount          string        `json:"AcctSelectorToAccount"`
	AcctSelectorFromSeg1Val        string        `json:"AcctSelectorFromSeg1Val"`
	AcctSelectorToSeg1Val          string        `json:"AcctSelectorToSeg1Val"`
	AcctSelectorFromSeg2Val        string        `json:"AcctSelectorFromSeg2Val"`
	AcctSelectorToSeg2Val          string        `json:"AcctSelectorToSeg2Val"`
	AcctSelectorFromSeg3Val        string        `json:"AcctSelectorFromSeg3Val"`
	AcctSelectorToSeg3Val          string        `json:"AcctSelectorToSeg3Val"`
	AcctSelectorFromSeg4Val        string        `json:"AcctSelectorFromSeg4Val"`
	AcctSelectorToSeg4Val          string        `json:"AcctSelectorToSeg4Val"`
	AcctSelectorFromSeg5Val        string        `json:"AcctSelectorFromSeg5Val"`
	AcctSelectorToSeg5Val          string        `json:"AcctSelectorToSeg5Val"`
	AcctSelectorFromSeg6Val        string        `json:"AcctSelectorFromSeg6Val"`
	AcctSelectorToSeg6Val          string        `json:"AcctSelectorToSeg6Val"`
	AcctSelectorFromSeg7Val        string        `json:"AcctSelectorFromSeg7Val"`
	AcctSelectorToSeg7Val          string        `json:"AcctSelectorToSeg7Val"`
	AcctSelectorFromSeg8Val        string        `json:"AcctSelectorFromSeg8Val"`
	AcctSelectorToSeg8Val          string        `json:"AcctSelectorToSeg8Val"`
	AcctSelectorFromSeg9Val        string        `json:"AcctSelectorFromSeg9Val"`
	AcctSelectorToSeg9Val          string        `json:"AcctSelectorToSeg9Val"`
	AcctSelectorFromSeg10Val       string        `json:"AcctSelectorFromSeg10Val"`
	AcctSelectorToSeg10Val         string        `json:"AcctSelectorToSeg10Val"`
	AcctSelectorOptionalField1     string        `json:"AcctSelectorOptionalField1"`
	AcctSelectorOptionalField2     string        `json:"AcctSelectorOptionalField2"`
	AcctSelectorOptionalField3     string        `json:"AcctSelectorOptionalField3"`
	AcctSelectorFromOpt1Val        string        `json:"AcctSelectorFromOpt1Val"`
	AcctSelectorToOpt1Val          string        `json:"AcctSelectorToOpt1Val"`
	AcctSelectorFromOpt2Val        string        `json:"AcctSelectorFromOpt2Val"`
	AcctSelectorToOpt2Val          string        `json:"AcctSelectorToOpt2Val"`
	AcctSelectorFromOpt3Val        string        `json:"AcctSelectorFromOpt3Val"`
	AcctSelectorToOpt3Val          string        `json:"AcctSelectorToOpt3Val"`
	AcctSelectorAcctType           int           `json:"AcctSelectorAcctType"`
	AcctSelectorFromAcctGroup      string        `json:"AcctSelectorFromAcctGroup"`
	AcctSelectorToAcctGroup        string        `json:"AcctSelectorToAcctGroup"`
	AcctSelectorQuantityAllowed    int           `json:"AcctSelectorQuantityAllowed"`
	NumberOfcreatedpreviewaccounts int           `json:"NumberOfcreatedpreviewaccounts"`
	RollupMembersInOtherAccounts   int           `json:"RollupMembersInOtherAccounts"`
	AccountAllocationInstructions  []interface{} `json:"AccountAllocationInstructions"`
	AccountValidCurrencies         []interface{} `json:"AccountValidCurrencies"`
	ControlAccountSubledgers       []interface{} `json:"ControlAccountSubledgers"`
	AccountOptionalFields          []struct {
		UnformattedAccount       string      `json:"UnformattedAccount"`
		OptionalField            string      `json:"OptionalField"`
		Value                    string      `json:"Value"`
		AccountOptionalFieldType string      `json:"AccountOptionalFieldType"`
		Length                   int         `json:"Length"`
		Decimals                 int         `json:"Decimals"`
		AllowBlank               bool        `json:"AllowBlank"`
		Validate                 bool        `json:"Validate"`
		ValueSet                 string      `json:"ValueSet"`
		TypedValueFieldIndex     int         `json:"TypedValueFieldIndex"`
		TextValue                string      `json:"TextValue"`
		AmountValue              float64     `json:"AmountValue"`
		NumberValue              int         `json:"NumberValue"`
		IntegerValue             int         `json:"IntegerValue"`
		YesNoValue               bool        `json:"YesNoValue"`
		DateValue                interface{} `json:"DateValue"`
		TimeValue                time.Time   `json:"TimeValue"`
		OptionalFieldDescription string      `json:"OptionalFieldDescription"`
		ValueDescription         string      `json:"ValueDescription"`
		UpdateOperation          string      `json:"UpdateOperation"`
	} `json:"AccountOptionalFields"`
	AccountTransactionOptionalFields []interface{} `json:"AccountTransactionOptionalFields"`
	RollupGroups                     []interface{} `json:"RollupGroups"`
	RollupMemberPreview              []interface{} `json:"RollupMemberPreview"`
	UpdateOperation                  string        `json:"UpdateOperation"`
}

type TaxRates []TaxRate

type TaxRate struct {
	TaxAuthority    string      `json:"TaxAuthority"`
	TransactionType string      `json:"TransactionType"`
	BuyerClass      int         `json:"BuyerClass"`
	ItemRate1       float64     `json:"ItemRate1"`
	ItemRate2       float64     `json:"ItemRate2"`
	ItemRate3       float64     `json:"ItemRate3"`
	ItemRate4       float64     `json:"ItemRate4"`
	ItemRate5       float64     `json:"ItemRate5"`
	ItemRate6       float64     `json:"ItemRate6"`
	ItemRate7       float64     `json:"ItemRate7"`
	ItemRate8       float64     `json:"ItemRate8"`
	ItemRate9       float64     `json:"ItemRate9"`
	ItemRate10      float64     `json:"ItemRate10"`
	LastMaintained  interface{} `json:"LastMaintained"`
	UpdateOperation string      `json:"UpdateOperation"`
}

type TaxGroups []TaxGroup

type TaxGroup struct {
	TaxGroupKey          string    `json:"TaxGroupKey"`
	TransactionType      string    `json:"TransactionType"`
	Description          string    `json:"Description"`
	TaxReportingCurrency string    `json:"TaxReportingCurrency"`
	TaxAuthority1        string    `json:"TaxAuthority1"`
	TaxAuthority2        string    `json:"TaxAuthority2"`
	TaxAuthority3        string    `json:"TaxAuthority3"`
	TaxAuthority4        string    `json:"TaxAuthority4"`
	TaxAuthority5        string    `json:"TaxAuthority5"`
	Taxable1             bool      `json:"Taxable1"`
	Taxable2             bool      `json:"Taxable2"`
	Taxable3             bool      `json:"Taxable3"`
	Taxable4             bool      `json:"Taxable4"`
	Taxable5             bool      `json:"Taxable5"`
	TaxCalculationMethod string    `json:"TaxCalculationMethod"`
	LastMaintained       time.Time `json:"LastMaintained"`
	Surtax1              bool      `json:"Surtax1"`
	Surtax2              bool      `json:"Surtax2"`
	Surtax3              bool      `json:"Surtax3"`
	Surtax4              bool      `json:"Surtax4"`
	Surtax5              bool      `json:"Surtax5"`
	SurtaxOnAuthority1   string    `json:"SurtaxOnAuthority1"`
	SurtaxOnAuthority2   string    `json:"SurtaxOnAuthority2"`
	SurtaxOnAuthority3   string    `json:"SurtaxOnAuthority3"`
	SurtaxOnAuthority4   string    `json:"SurtaxOnAuthority4"`
	SurtaxOnAuthority5   string    `json:"SurtaxOnAuthority5"`
	TaxReportingRateType string    `json:"TaxReportingRateType"`
	UpdateOperation      string    `json:"UpdateOperation"`
}

type PostedTransactions []PostedTransaction

type PostedTransaction struct {
	AccountNumber               string    `json:"AccountNumber"`
	FiscalYear                  string    `json:"FiscalYear"`
	FiscalPeriod                string    `json:"FiscalPeriod"`
	SourceCurrencyCode          string    `json:"SourceCurrencyCode"`
	SourceLedgerCode            string    `json:"SourceLedgerCode"`
	SourceTypeCode              string    `json:"SourceTypeCode"`
	PostingSequenceNumber       int       `json:"PostingSequenceNumber"`
	DetailCount                 int       `json:"DetailCount"`
	JournalDate                 time.Time `json:"JournalDate"`
	BatchNumber                 string    `json:"BatchNumber"`
	JournalEntryNumber          string    `json:"JournalEntryNumber"`
	JournalTransactionNumber    int       `json:"JournalTransactionNumber"`
	ConsolidationOccurredOnPost string    `json:"ConsolidationOccurredOnPost"`
	CompanyID                   string    `json:"CompanyID"`
	JournalDetailDescription    string    `json:"JournalDetailDescription"`
	JournalDetailReference      string    `json:"JournalDetailReference"`
	JournalTransactionAmount    float64   `json:"JournalTransactionAmount"`
	JournalTransactionQuantity  float64   `json:"JournalTransactionQuantity"`
	NbrOfSourceCurrencyDecimals string    `json:"NbrOfSourceCurrencyDecimals"`
	SourceCurrencyAmount        float64   `json:"SourceCurrencyAmount"`
	HomeCurrencyCode            string    `json:"HomeCurrencyCode"`
	CurrencyRateTableType       string    `json:"CurrencyRateTableType"`
	SCURNCODE                   string    `json:"SCURNCODE"`
	DateOfCurrencyRateSelected  time.Time `json:"DateOfCurrencyRateSelected"`
	CurrencyRateForConversion   int       `json:"CurrencyRateForConversion"`
	CurrencyRateSpreadAllowed   float64   `json:"CurrencyRateSpreadAllowed"`
	CodeForRateDateMatching     string    `json:"CodeForRateDateMatching"`
	CurrencyRateOperator        string    `json:"CurrencyRateOperator"`
	DrillDownType               int       `json:"DrillDownType"`
	DrillDownLinkNumber         int       `json:"DrillDownLinkNumber"`
	DrillDownApplicationSource  string    `json:"DrillDownApplicationSource"`
	ReportCurrencyAmount        float64   `json:"ReportCurrencyAmount"`
	NumberOfOptionalFields      int       `json:"NumberOfOptionalFields"`
	DocumentDate                time.Time `json:"DocumentDate"`
	TaxReportingStatus          int       `json:"TaxReportingStatus"`
	TaxAuthority                string    `json:"TaxAuthority"`
	TaxAccountType              string    `json:"TaxAccountType"`
	UpdateOperation             string    `json:"UpdateOperation"`
}

type PostingJournalDetails []PostingJournalDetail

type PostingJournalDetail struct {
	Postingsequencenumber       int       `json:"Postingsequencenumber"`
	BatchNumber                 string    `json:"BatchNumber"`
	Journalentrynumber          string    `json:"Journalentrynumber"`
	Journaltransactionnumber    int       `json:"Journaltransactionnumber"`
	Journaldate                 time.Time `json:"Journaldate"`
	Fiscalyear                  string    `json:"Fiscalyear"`
	Fiscalperiod                string    `json:"Fiscalperiod"`
	SourceLedgerCode            string    `json:"SourceLedgerCode"`
	SourceTypeCode              string    `json:"SourceTypeCode"`
	ConsolidationoccurredOnpost string    `json:"ConsolidationoccurredOnpost"`
	AccountNumber               string    `json:"AccountNumber"`
	CompanyID                   string    `json:"CompanyID"`
	Journaldetaildescription    string    `json:"Journaldetaildescription"`
	Journaldetailreference      string    `json:"Journaldetailreference"`
	Journaltransactionamount    float64   `json:"Journaltransactionamount"`
	Journaltransactionquantity  float64   `json:"Journaltransactionquantity"`
	NbrOfsourcecurrencydecimals string    `json:"NbrOfsourcecurrencydecimals"`
	Sourcecurrencyamount        float64   `json:"Sourcecurrencyamount"`
	Homecurrencycode            string    `json:"Homecurrencycode"`
	Currencyratetabletype       string    `json:"Currencyratetabletype"`
	Sourcecurrencycode          string    `json:"Sourcecurrencycode"`
	DateOfcurrencyrateselected  time.Time `json:"DateOfcurrencyrateselected"`
	CurrencyrateForconversion   int       `json:"CurrencyrateForconversion"`
	Currencyratespreadallowed   float64   `json:"Currencyratespreadallowed"`
	CodeForratedatematching     string    `json:"CodeForratedatematching"`
	Currencyrateoperator        string    `json:"Currencyrateoperator"`
	Printedstatuscode           string    `json:"Printedstatuscode"`
	PostingDate                 time.Time `json:"PostingDate"`
	Reportcurrencyamount        float64   `json:"Reportcurrencyamount"`
	NumberOfOptionalFields      int       `json:"NumberOfOptionalFields"`
	Originator                  string    `json:"Originator"`
	AutoReversal                string    `json:"AutoReversal"`
	Destination                 string    `json:"Destination"`
	RouteNumber                 int       `json:"RouteNumber"`
	DocumentDate                time.Time `json:"DocumentDate"`
	TaxAuthority                string    `json:"TaxAuthority"`
	TaxAccountType              string    `json:"TaxAccountType"`
	UpdateOperation             string    `json:"UpdateOperation"`
}

type GLJournalBatch struct {
	BatchNumber                      string    `json:"BatchNumber"`
	ActiveSwitch                     string    `json:"ActiveSwitch"`
	Description                      string    `json:"Description"`
	SourceLedger                     string    `json:"SourceLedger"`
	DateCreated                      time.Time `json:"DateCreated"`
	DateLastEdited                   time.Time `json:"DateLastEdited"`
	JournalBatchType                 string    `json:"JournalBatchType"`
	Status                           string    `json:"Status"`
	PostingSequence                  int       `json:"PostingSequence"`
	Debits                           int       `json:"Debits"`
	Credits                          int       `json:"Credits"`
	QuantityTotal                    int       `json:"QuantityTotal"`
	NumberOfEntries                  int       `json:"NumberOfEntries"`
	NextEntryNumber                  int       `json:"NextEntryNumber"`
	NumberOfErrors                   int       `json:"NumberOfErrors"`
	OriginalStatus                   string    `json:"OriginalStatus"`
	Printed                          string    `json:"Printed"`
	ICTRelated                       string    `json:"ICTRelated"`
	RevaluationRecognizedBatch       string    `json:"RevaluationRecognizedBatch"`
	EligibleForEditSwitch            string    `json:"EligibleForEditSwitch"`
	EligibleForDeleteSwitch          string    `json:"EligibleForDeleteSwitch"`
	EligibleForPostingSwitch         string    `json:"EligibleForPostingSwitch"`
	EligibleForPrintingSwitch        string    `json:"EligibleForPrintingSwitch"`
	EligibleForProvisionalPostSwitch string    `json:"EligibleForProvisionalPostSwitch"`
	ReadyToPost                      string    `json:"ReadyToPost"`
	LockBatchSwitch                  string    `json:"LockBatchSwitch"`
	JournalHeaders                   []struct {
		BatchNumber                    string    `json:"BatchNumber"`
		EntryNumber                    string    `json:"EntryNumber"`
		Originator                     string    `json:"Originator"`
		SourceLedger                   string    `json:"SourceLedger"`
		SourceType                     string    `json:"SourceType"`
		FiscalYear                     string    `json:"FiscalYear"`
		FiscalPeriod                   string    `json:"FiscalPeriod"`
		AutoReversal                   string    `json:"AutoReversal"`
		Description                    string    `json:"Description"`
		Debits                         int       `json:"Debits"`
		Credits                        int       `json:"Credits"`
		Quantity                       int       `json:"Quantity"`
		PostingDate                    time.Time `json:"PostingDate"`
		DrillDownType                  int       `json:"DrillDownType"`
		DrillDownLinkNumber            int       `json:"DrillDownLinkNumber"`
		DrillDownApplicationSource     string    `json:"DrillDownApplicationSource"`
		OutOfBalanceBy                 int       `json:"OutOfBalanceBy"`
		SpecificReversalYear           string    `json:"SpecificReversalYear"`
		SpecificReversalPeriod         string    `json:"SpecificReversalPeriod"`
		ErrorBatch                     int       `json:"ErrorBatch"`
		ErrorEntry                     int       `json:"ErrorEntry"`
		NumberOfDetails                int       `json:"NumberOfDetails"`
		Processswitches                string    `json:"Processswitches"`
		EnteredBy                      string    `json:"EnteredBy"`
		DocumentDate                   time.Time `json:"DocumentDate"`
		OrigExists                     int       `json:"OrigExists"`
		OrigDescription                string    `json:"OrigDescription"`
		OrigStatus                     int       `json:"OrigStatus"`
		OrigMulticurrencySwitch        int       `json:"OrigMulticurrencySwitch"`
		OrigHomeCurrency               string    `json:"OrigHomeCurrency"`
		OrigHomeCurrencyDecimals       int       `json:"OrigHomeCurrencyDecimals"`
		OrigQtySwitch                  int       `json:"OrigQtySwitch"`
		OrigQtyDecimals                int       `json:"OrigQtyDecimals"`
		SourceCodeExists               int       `json:"SourceCodeExists"`
		SourceCodeDescription          string    `json:"SourceCodeDescription"`
		TaxGroup                       string    `json:"TaxGroup"`
		EntryType                      string    `json:"EntryType"`
		DoNotCalculationTax            string    `json:"DoNotCalculationTax"`
		CustomerVendorNumber           string    `json:"CustomerVendorNumber"`
		DocumentType                   string    `json:"DocumentType"`
		DocumentNumber                 string    `json:"DocumentNumber"`
		TaxAuthority1                  string    `json:"TaxAuthority1"`
		TaxAuthority2                  string    `json:"TaxAuthority2"`
		TaxAuthority3                  string    `json:"TaxAuthority3"`
		TaxAuthority4                  string    `json:"TaxAuthority4"`
		TaxAuthority5                  string    `json:"TaxAuthority5"`
		TaxVendorClass1                int       `json:"TaxVendorClass1"`
		TaxVendorClass2                int       `json:"TaxVendorClass2"`
		TaxVendorClass3                int       `json:"TaxVendorClass3"`
		TaxVendorClass4                int       `json:"TaxVendorClass4"`
		TaxVendorClass5                int       `json:"TaxVendorClass5"`
		TaxItemClass1                  int       `json:"TaxItemClass1"`
		TaxItemClass2                  int       `json:"TaxItemClass2"`
		TaxItemClass3                  int       `json:"TaxItemClass3"`
		TaxItemClass4                  int       `json:"TaxItemClass4"`
		TaxItemClass5                  int       `json:"TaxItemClass5"`
		TaxBaseAmount1                 int       `json:"TaxBaseAmount1"`
		TaxBaseAmount2                 int       `json:"TaxBaseAmount2"`
		TaxBaseAmount3                 int       `json:"TaxBaseAmount3"`
		TaxBaseAmount4                 int       `json:"TaxBaseAmount4"`
		TaxBaseAmount5                 int       `json:"TaxBaseAmount5"`
		TaxAmount1                     int       `json:"TaxAmount1"`
		TaxAmount2                     int       `json:"TaxAmount2"`
		TaxAmount3                     int       `json:"TaxAmount3"`
		TaxAmount4                     int       `json:"TaxAmount4"`
		TaxAmount5                     int       `json:"TaxAmount5"`
		TaxExpenseAmount1              int       `json:"TaxExpenseAmount1"`
		TaxExpenseAmount2              int       `json:"TaxExpenseAmount2"`
		TaxExpenseAmount3              int       `json:"TaxExpenseAmount3"`
		TaxExpenseAmount4              int       `json:"TaxExpenseAmount4"`
		TaxExpenseAmount5              int       `json:"TaxExpenseAmount5"`
		TaxRecoverableAmount1          int       `json:"TaxRecoverableAmount1"`
		TaxRecoverableAmount2          int       `json:"TaxRecoverableAmount2"`
		TaxRecoverableAmount3          int       `json:"TaxRecoverableAmount3"`
		TaxRecoverableAmount4          int       `json:"TaxRecoverableAmount4"`
		TaxRecoverableAmount5          int       `json:"TaxRecoverableAmount5"`
		TaxAllocatedAmount1            int       `json:"TaxAllocatedAmount1"`
		TaxAllocatedAmount2            int       `json:"TaxAllocatedAmount2"`
		TaxAllocatedAmount3            int       `json:"TaxAllocatedAmount3"`
		TaxAllocatedAmount4            int       `json:"TaxAllocatedAmount4"`
		TaxAllocatedAmount5            int       `json:"TaxAllocatedAmount5"`
		TaxReportingAmount1            int       `json:"TaxReportingAmount1"`
		TaxReportingAmount2            int       `json:"TaxReportingAmount2"`
		TaxReportingAmount3            int       `json:"TaxReportingAmount3"`
		TaxReportingAmount4            int       `json:"TaxReportingAmount4"`
		TaxReportingAmount5            int       `json:"TaxReportingAmount5"`
		TaxReportingExpensed1          int       `json:"TaxReportingExpensed1"`
		TaxReportingExpensed2          int       `json:"TaxReportingExpensed2"`
		TaxReportingExpensed3          int       `json:"TaxReportingExpensed3"`
		TaxReportingExpensed4          int       `json:"TaxReportingExpensed4"`
		TaxReportingExpensed5          int       `json:"TaxReportingExpensed5"`
		TaxReportingRecoverableAmount1 int       `json:"TaxReportingRecoverableAmount1"`
		TaxReportingRecoverableAmount2 int       `json:"TaxReportingRecoverableAmount2"`
		TaxReportingRecoverableAmount3 int       `json:"TaxReportingRecoverableAmount3"`
		TaxReportingRecoverableAmount4 int       `json:"TaxReportingRecoverableAmount4"`
		TaxReportingRecoverableAmount5 int       `json:"TaxReportingRecoverableAmount5"`
		TaxReportingAllocatedAmount1   int       `json:"TaxReportingAllocatedAmount1"`
		TaxReportingAllocatedAmount2   int       `json:"TaxReportingAllocatedAmount2"`
		TaxReportingAllocatedAmount3   int       `json:"TaxReportingAllocatedAmount3"`
		TaxReportingAllocatedAmount4   int       `json:"TaxReportingAllocatedAmount4"`
		TaxReportingAllocatedAmount5   int       `json:"TaxReportingAllocatedAmount5"`
		TaxReportingCurrencyCode       string    `json:"TaxReportingCurrencyCode"`
		TaxReportingRate               int       `json:"TaxReportingRate"`
		TaxReportingRateType           string    `json:"TaxReportingRateType"`
		TaxReportingRateDate           time.Time `json:"TaxReportingRateDate"`
		TaxReportingRateOperation      string    `json:"TaxReportingRateOperation"`
		TaxExpenseAccount1             string    `json:"TaxExpenseAccount1"`
		TaxExpenseAccount2             string    `json:"TaxExpenseAccount2"`
		TaxExpenseAccount3             string    `json:"TaxExpenseAccount3"`
		TaxExpenseAccount4             string    `json:"TaxExpenseAccount4"`
		TaxExpenseAccount5             string    `json:"TaxExpenseAccount5"`
		TaxRecoverableAccount1         string    `json:"TaxRecoverableAccount1"`
		TaxRecoverableAccount2         string    `json:"TaxRecoverableAccount2"`
		TaxRecoverableAccount3         string    `json:"TaxRecoverableAccount3"`
		TaxRecoverableAccount4         string    `json:"TaxRecoverableAccount4"`
		TaxRecoverableAccount5         string    `json:"TaxRecoverableAccount5"`
		TaxRate1                       int       `json:"TaxRate1"`
		TaxRate2                       int       `json:"TaxRate2"`
		TaxRate3                       int       `json:"TaxRate3"`
		TaxRate4                       int       `json:"TaxRate4"`
		TaxRate5                       int       `json:"TaxRate5"`
		FunctionalTaxAmount1           int       `json:"FunctionalTaxAmount1"`
		FunctionalTaxAmount2           int       `json:"FunctionalTaxAmount2"`
		FunctionalTaxAmount3           int       `json:"FunctionalTaxAmount3"`
		FunctionalTaxAmount4           int       `json:"FunctionalTaxAmount4"`
		FunctionalTaxAmount5           int       `json:"FunctionalTaxAmount5"`
		FunctionalTaxBaseAmount1       int       `json:"FunctionalTaxBaseAmount1"`
		FunctionalTaxBaseAmount2       int       `json:"FunctionalTaxBaseAmount2"`
		FunctionalTaxBaseAmount3       int       `json:"FunctionalTaxBaseAmount3"`
		FunctionalTaxBaseAmount4       int       `json:"FunctionalTaxBaseAmount4"`
		FunctionalTaxBaseAmount5       int       `json:"FunctionalTaxBaseAmount5"`
		FunctionalExpensedAmount1      int       `json:"FunctionalExpensedAmount1"`
		FunctionalExpensedAmount2      int       `json:"FunctionalExpensedAmount2"`
		FunctionalExpensedAmount3      int       `json:"FunctionalExpensedAmount3"`
		FunctionalExpensedAmount4      int       `json:"FunctionalExpensedAmount4"`
		FunctionalExpensedAmount5      int       `json:"FunctionalExpensedAmount5"`
		FunctionalRecoverableAmount1   int       `json:"FunctionalRecoverableAmount1"`
		FunctionalRecoverableAmount2   int       `json:"FunctionalRecoverableAmount2"`
		FunctionalRecoverableAmount3   int       `json:"FunctionalRecoverableAmount3"`
		FunctionalRecoverableAmount4   int       `json:"FunctionalRecoverableAmount4"`
		FunctionalRecoverableAmount5   int       `json:"FunctionalRecoverableAmount5"`
		FunctionalAllocatedAmount1     int       `json:"FunctionalAllocatedAmount1"`
		FunctionalAllocatedAmount2     int       `json:"FunctionalAllocatedAmount2"`
		FunctionalAllocatedAmount3     int       `json:"FunctionalAllocatedAmount3"`
		FunctionalAllocatedAmount4     int       `json:"FunctionalAllocatedAmount4"`
		FunctionalAllocatedAmount5     int       `json:"FunctionalAllocatedAmount5"`
		InvoicetotalInTaxGroupCurre    int       `json:"InvoicetotalInTaxGroupCurre"`
		InvoicetotalInfunctionalCurr   int       `json:"InvoicetotalInfunctionalCurr"`
		TaxGroupDescription            string    `json:"TaxGroupDescription"`
		TaxAuthorityDescription1       string    `json:"TaxAuthorityDescription1"`
		TaxAuthorityDescription2       string    `json:"TaxAuthorityDescription2"`
		TaxAuthorityDescription3       string    `json:"TaxAuthorityDescription3"`
		TaxAuthorityDescription4       string    `json:"TaxAuthorityDescription4"`
		TaxAuthorityDescription5       string    `json:"TaxAuthorityDescription5"`
		TaxReportingCurrencyCodeDesc   string    `json:"TaxReportingCurrencyCodeDesc"`
		RateTypeDescription            string    `json:"RateTypeDescription"`
		CustomerVendorName             string    `json:"CustomerVendorName"`
		JournalDetails                 []struct {
			BatchNumber                  string    `json:"BatchNumber"`
			EntryNumber                  string    `json:"EntryNumber"`
			TransactionNumber            string    `json:"TransactionNumber"`
			Destination                  string    `json:"Destination"`
			RouteNumber                  int       `json:"RouteNumber"`
			AccountNumber                string    `json:"AccountNumber"`
			CompanyID                    string    `json:"CompanyID"`
			Amount                       int       `json:"Amount"`
			Quantity                     int       `json:"Quantity"`
			SourceCurrencyDecimals       string    `json:"SourceCurrencyDecimals"`
			SourceCurrencyAmount         int       `json:"SourceCurrencyAmount"`
			HomeCurrency                 string    `json:"HomeCurrency"`
			CurrencyRateTable            string    `json:"CurrencyRateTable"`
			SourceCurrency               string    `json:"SourceCurrency"`
			CurrencyRateDate             time.Time `json:"CurrencyRateDate"`
			CurrencyRate                 int       `json:"CurrencyRate"`
			CurrencyRateSpread           int       `json:"CurrencyRateSpread"`
			CurrencyRateDateMatching     string    `json:"CurrencyRateDateMatching"`
			CurrencyRateOperator         string    `json:"CurrencyRateOperator"`
			Description                  string    `json:"Description"`
			Reference                    string    `json:"Reference"`
			JournalDate                  time.Time `json:"JournalDate"`
			SourceLedger                 string    `json:"SourceLedger"`
			SourceType                   string    `json:"SourceType"`
			Comment                      string    `json:"Comment"`
			NumberOfOptionalFields       int       `json:"NumberOfOptionalFields"`
			Processswitches              string    `json:"Processswitches"`
			DestExists                   int       `json:"DestExists"`
			DestDescription              string    `json:"DestDescription"`
			DestStatus                   int       `json:"DestStatus"`
			DestMulticurrencySwitch      int       `json:"DestMulticurrencySwitch"`
			DestHomeCurrency             string    `json:"DestHomeCurrency"`
			DestHomeCurrencyDecimals     int       `json:"DestHomeCurrencyDecimals"`
			DestQtySwitch                int       `json:"DestQtySwitch"`
			DestQtyDecimals              int       `json:"DestQtyDecimals"`
			DestOptionalFlds             int       `json:"DestOptionalFlds"`
			RouteExists                  int       `json:"RouteExists"`
			RouteDescription             string    `json:"RouteDescription"`
			RouteStatus                  int       `json:"RouteStatus"`
			SourceCodeExists             int       `json:"SourceCodeExists"`
			SourceCodeDescription        string    `json:"SourceCodeDescription"`
			AcctExists                   int       `json:"AcctExists"`
			AcctFormatted                string    `json:"AcctFormatted"`
			AcctDescription              string    `json:"AcctDescription"`
			AcctStatus                   int       `json:"AcctStatus"`
			AcctMulticurrencySwitch      int       `json:"AcctMulticurrencySwitch"`
			AcctSpecificCurrenciesSwitch int       `json:"AcctSpecificCurrenciesSwitch"`
			AcctControlSwitch            int       `json:"AcctControlSwitch"`
			AcctQtySwitch                int       `json:"AcctQtySwitch"`
			AcctOptionalFlds             int       `json:"AcctOptionalFlds"`
			AcctTransactionOptionalFlds  int       `json:"AcctTransactionOptionalFlds"`
			AcctUnitOfMeasure            string    `json:"AcctUnitOfMeasure"`
			TaxAuthority                 string    `json:"TaxAuthority"`
			TaxAccountType               int       `json:"TaxAccountType"`
			JournalDetailOptionalFields  []struct {
				BatchNumber                    string    `json:"BatchNumber"`
				EntryNumber                    string    `json:"EntryNumber"`
				TransactionNumber              string    `json:"TransactionNumber"`
				OptionalField                  string    `json:"OptionalField"`
				Value                          string    `json:"Value"`
				JournalDetailOptionalFieldType string    `json:"JournalDetailOptionalFieldType"`
				Length                         int       `json:"Length"`
				Decimals                       int       `json:"Decimals"`
				AllowBlank                     bool      `json:"AllowBlank"`
				Validate                       bool      `json:"Validate"`
				ValueSet                       string    `json:"ValueSet"`
				TypedValueFieldIndex           int       `json:"TypedValueFieldIndex"`
				TextValue                      string    `json:"TextValue"`
				AmountValue                    int       `json:"AmountValue"`
				NumberValue                    int       `json:"NumberValue"`
				IntegerValue                   int       `json:"IntegerValue"`
				YesNoValue                     bool      `json:"YesNoValue"`
				DateValue                      time.Time `json:"DateValue"`
				TimeValue                      time.Time `json:"TimeValue"`
				OptionalFieldDescription       string    `json:"OptionalFieldDescription"`
				ValueDescription               string    `json:"ValueDescription"`
				UpdateOperation                string    `json:"UpdateOperation"`
				Warnings                       []struct {
					Message        string `json:"Message"`
					Priority       string `json:"Priority"`
					PriorityString string `json:"PriorityString"`
					Tag            struct {
					} `json:"Tag"`
				} `json:"Warnings"`
				ETag           string `json:"ETag"`
				IsDeleted      bool   `json:"IsDeleted"`
				IsNewLine      bool   `json:"IsNewLine"`
				HasChanged     bool   `json:"HasChanged"`
				DisplayIndex   int    `json:"DisplayIndex"`
				ChangeSequence int    `json:"ChangeSequence"`
				PreviousKey    string `json:"PreviousKey"`
				Licenses       struct {
				} `json:"Licenses"`
				IsSelected bool `json:"IsSelected"`
			} `json:"JournalDetailOptionalFields"`
			UpdateOperation string `json:"UpdateOperation"`
			Warnings        []struct {
				Message        string `json:"Message"`
				Priority       string `json:"Priority"`
				PriorityString string `json:"PriorityString"`
				Tag            struct {
				} `json:"Tag"`
			} `json:"Warnings"`
			ETag           string `json:"ETag"`
			IsDeleted      bool   `json:"IsDeleted"`
			IsNewLine      bool   `json:"IsNewLine"`
			HasChanged     bool   `json:"HasChanged"`
			DisplayIndex   int    `json:"DisplayIndex"`
			ChangeSequence int    `json:"ChangeSequence"`
			PreviousKey    string `json:"PreviousKey"`
			Licenses       struct {
			} `json:"Licenses"`
			IsSelected bool `json:"IsSelected"`
		} `json:"JournalDetails"`
		UpdateOperation string `json:"UpdateOperation"`
		Warnings        []struct {
			Message        string `json:"Message"`
			Priority       string `json:"Priority"`
			PriorityString string `json:"PriorityString"`
			Tag            struct {
			} `json:"Tag"`
		} `json:"Warnings"`
		ETag           string `json:"ETag"`
		IsDeleted      bool   `json:"IsDeleted"`
		IsNewLine      bool   `json:"IsNewLine"`
		HasChanged     bool   `json:"HasChanged"`
		DisplayIndex   int    `json:"DisplayIndex"`
		ChangeSequence int    `json:"ChangeSequence"`
		PreviousKey    string `json:"PreviousKey"`
		Licenses       struct {
		} `json:"Licenses"`
		IsSelected bool `json:"IsSelected"`
	} `json:"JournalHeaders"`
	UpdateOperation string `json:"UpdateOperation"`
}
