package sage300

import "time"

type GLAccounts []GLAccount

type GLAccount struct {
	UnformattedAccount             string        `json:"UnformattedAccount"`
	DateCreated                    time.Time     `json:"DateCreated"`
	Description                    string        `json:"Description"`
	AccountType                    string        `json:"AccountType"`
	NormalBalanceDRCR              string        `json:"NormalBalanceDRCR"`
	Status                         string        `json:"Status"`
	PostToAccount                  string        `json:"PostToAccount"`
	QuantitiesAllowed              string        `json:"QuantitiesAllowed"`
	UnitOfMeasure                  string        `json:"UnitOfMeasure"`
	AllocationsAllowed             string        `json:"AllocationsAllowed"`
	AllocOffsetAccount             string        `json:"AllocOffsetAccount"`
	AllocSourceType                string        `json:"AllocSourceType"`
	Multicurrency                  string        `json:"Multicurrency"`
	SpecificCurrency               string        `json:"SpecificCurrency"`
	ControlAccount                 string        `json:"ControlAccount"`
	AllocationPercentTotal         float64       `json:"AllocationPercentTotal"`
	StructureCode                  string        `json:"StructureCode"`
	YearLastClosed                 int           `json:"YearLastClosed"`
	AccountNumber                  string        `json:"AccountNumber"`
	AccountSegmentCode1            string        `json:"AccountSegmentCode1"`
	AccountSegmentCode2            string        `json:"AccountSegmentCode2"`
	AccountSegmentCode3            string        `json:"AccountSegmentCode3"`
	AccountSegmentCode4            string        `json:"AccountSegmentCode4"`
	AccountSegmentCode5            string        `json:"AccountSegmentCode5"`
	AccountSegmentCode6            string        `json:"AccountSegmentCode6"`
	AccountSegmentCode7            string        `json:"AccountSegmentCode7"`
	AccountSegmentCode8            string        `json:"AccountSegmentCode8"`
	AccountSegmentCode9            string        `json:"AccountSegmentCode9"`
	AccountSegmentCode10           string        `json:"AccountSegmentCode10"`
	SegmentCode                    string        `json:"SegmentCode"`
	PostToSegmentID                string        `json:"PostToSegmentID"`
	DefaultCurrencyCode            string        `json:"DefaultCurrencyCode"`
	NumberOfOptionalFields         int           `json:"NumberOfOptionalFields"`
	TransactionOptionalFields      int           `json:"TransactionOptionalFields"`
	ProcessSwitch                  string        `json:"ProcessSwitch"`
	AccountGroupCode               string        `json:"AccountGroupCode"`
	AccountGroupSortCode           string        `json:"AccountGroupSortCode"`
	RollupSwitch                   string        `json:"RollupSwitch"`
	RollupMemberNonRollup          string        `json:"RollupMemberNonRollup"`
	AcctSelectorFromAccount        string        `json:"AcctSelectorFromAccount"`
	AcctSelectorToAccount          string        `json:"AcctSelectorToAccount"`
	AcctSelectorFromSeg1Val        string        `json:"AcctSelectorFromSeg1Val"`
	AcctSelectorToSeg1Val          string        `json:"AcctSelectorToSeg1Val"`
	AcctSelectorFromSeg2Val        string        `json:"AcctSelectorFromSeg2Val"`
	AcctSelectorToSeg2Val          string        `json:"AcctSelectorToSeg2Val"`
	AcctSelectorFromSeg3Val        string        `json:"AcctSelectorFromSeg3Val"`
	AcctSelectorToSeg3Val          string        `json:"AcctSelectorToSeg3Val"`
	AcctSelectorFromSeg4Val        string        `json:"AcctSelectorFromSeg4Val"`
	AcctSelectorToSeg4Val          string        `json:"AcctSelectorToSeg4Val"`
	AcctSelectorFromSeg5Val        string        `json:"AcctSelectorFromSeg5Val"`
	AcctSelectorToSeg5Val          string        `json:"AcctSelectorToSeg5Val"`
	AcctSelectorFromSeg6Val        string        `json:"AcctSelectorFromSeg6Val"`
	AcctSelectorToSeg6Val          string        `json:"AcctSelectorToSeg6Val"`
	AcctSelectorFromSeg7Val        string        `json:"AcctSelectorFromSeg7Val"`
	AcctSelectorToSeg7Val          string        `json:"AcctSelectorToSeg7Val"`
	AcctSelectorFromSeg8Val        string        `json:"AcctSelectorFromSeg8Val"`
	AcctSelectorToSeg8Val          string        `json:"AcctSelectorToSeg8Val"`
	AcctSelectorFromSeg9Val        string        `json:"AcctSelectorFromSeg9Val"`
	AcctSelectorToSeg9Val          string        `json:"AcctSelectorToSeg9Val"`
	AcctSelectorFromSeg10Val       string        `json:"AcctSelectorFromSeg10Val"`
	AcctSelectorToSeg10Val         string        `json:"AcctSelectorToSeg10Val"`
	AcctSelectorOptionalField1     string        `json:"AcctSelectorOptionalField1"`
	AcctSelectorOptionalField2     string        `json:"AcctSelectorOptionalField2"`
	AcctSelectorOptionalField3     string        `json:"AcctSelectorOptionalField3"`
	AcctSelectorFromOpt1Val        string        `json:"AcctSelectorFromOpt1Val"`
	AcctSelectorToOpt1Val          string        `json:"AcctSelectorToOpt1Val"`
	AcctSelectorFromOpt2Val        string        `json:"AcctSelectorFromOpt2Val"`
	AcctSelectorToOpt2Val          string        `json:"AcctSelectorToOpt2Val"`
	AcctSelectorFromOpt3Val        string        `json:"AcctSelectorFromOpt3Val"`
	AcctSelectorToOpt3Val          string        `json:"AcctSelectorToOpt3Val"`
	AcctSelectorAcctType           int           `json:"AcctSelectorAcctType"`
	AcctSelectorFromAcctGroup      string        `json:"AcctSelectorFromAcctGroup"`
	AcctSelectorToAcctGroup        string        `json:"AcctSelectorToAcctGroup"`
	AcctSelectorQuantityAllowed    int           `json:"AcctSelectorQuantityAllowed"`
	NumberOfcreatedpreviewaccounts int           `json:"NumberOfcreatedpreviewaccounts"`
	RollupMembersInOtherAccounts   int           `json:"RollupMembersInOtherAccounts"`
	AccountAllocationInstructions  []interface{} `json:"AccountAllocationInstructions"`
	AccountValidCurrencies         []interface{} `json:"AccountValidCurrencies"`
	ControlAccountSubledgers       []interface{} `json:"ControlAccountSubledgers"`
	AccountOptionalFields          []struct {
		UnformattedAccount       string      `json:"UnformattedAccount"`
		OptionalField            string      `json:"OptionalField"`
		Value                    string      `json:"Value"`
		AccountOptionalFieldType string      `json:"AccountOptionalFieldType"`
		Length                   int         `json:"Length"`
		Decimals                 int         `json:"Decimals"`
		AllowBlank               bool        `json:"AllowBlank"`
		Validate                 bool        `json:"Validate"`
		ValueSet                 string      `json:"ValueSet"`
		TypedValueFieldIndex     int         `json:"TypedValueFieldIndex"`
		TextValue                string      `json:"TextValue"`
		AmountValue              float64     `json:"AmountValue"`
		NumberValue              int         `json:"NumberValue"`
		IntegerValue             int         `json:"IntegerValue"`
		YesNoValue               bool        `json:"YesNoValue"`
		DateValue                interface{} `json:"DateValue"`
		TimeValue                time.Time   `json:"TimeValue"`
		OptionalFieldDescription string      `json:"OptionalFieldDescription"`
		ValueDescription         string      `json:"ValueDescription"`
		UpdateOperation          string      `json:"UpdateOperation"`
	} `json:"AccountOptionalFields"`
	AccountTransactionOptionalFields []interface{} `json:"AccountTransactionOptionalFields"`
	RollupGroups                     []interface{} `json:"RollupGroups"`
	RollupMemberPreview              []interface{} `json:"RollupMemberPreview"`
	UpdateOperation                  string        `json:"UpdateOperation"`
}
